; This file was auto-generated by drush make

core = 7.x
api = 2

; Projects

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[transliteration][subdir] = "contrib"
projects[transliteration][version] = "3.1"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[strongarm][subdir] = "contrib"
projects[strongarm][version] = "2.0"

